<?php
/** 
 * Load JS
 */
function extended_uportal_header_process_page() {
  $params = drupal_get_query_parameters();
  $cacheBuster = isset($params['test']) ? time() : date("ymd");
  drupal_add_js('/commun/extended-uportal-header.min.js?c='.$cacheBuster, 'external');
  drupal_add_js('/commun/extended-uportal-footer.min.js?c='.$cacheBuster, 'external');
}
/**
 * Declare custom blocks
 */
function extended_uportal_header_boot() {
  $params = drupal_get_query_parameters();
  if(isset($params['portal_domain'])){
    setcookie('extended_uportal_header_portal_domain',$params['portal_domain'],[
      'secure'=>true,
      'httponly'=>true
    ]);
  }
}
/**
 * Declare custom blocks
 */
function extended_uportal_header_block_info() {
  $blocks['extended_uportal_header'] = array(
    'info' => t('Extended Uportal header component'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['extended_uportal_footer'] = array(
    'info' => t('Extended Uportal footer component'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Define custom blocks
 */
function extended_uportal_header_block_view($delta) {
  $actual_link = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
  switch ($delta) {
    case 'extended_uportal_header':
      $portal_domain = $_COOKIE['extended_uportal_header_portal_domain'] ?? false;
      $block['content']['#markup'] ='<extended-uportal-header
                                      messages=\'[{"locales": ["fr", "fr-FR"], "messages": { "message": {"header": {"login": "Connexion ENT" } }}}]\'
                                      '.($portal_domain?'domain='.$portal_domain:'').'
                                      service-name="Formulaires d\'enquête"
                                      context-api-url="/portail" 
                                      sign-out-url="/portail/Logout" 
                                      default-org-logo-path="/annuaire_images/default_banner_v1.jpg"
                                      default-avatar-path="/images/icones/noPictureUser.svg"
                                      default-org-icon-path="/images/partners/netocentre-simple.svg" 
                                      favorite-api-url="/portail/api/layout" 
                                      layout-api-url="/portail/api/v4-3/dlm/layout.json" 
                                      organization-api-url="/change-etablissement/rest/v2/structures/structs/" 
                                      portlet-api-url="/portail/api/v4-3/dlm/portletRegistry.json?category=All%20categories" 
                                      user-info-api-url="/portail/api/v5-1/userinfo?claims=private,name,ESCOSIRENCourant,ESCOSIREN,picture&groups="
                                      session-api-url="/portail/api/session.json" 
                                      user-info-portlet-url="/portail/api/ExternalURLStats?fname=ESCO-MCE&amp;service=/MCE"
                                      template-api-path="/commun/portal_template_api.tpl.json" 
                                      switch-org-portlet-url="/portail/p/etablissement-swapper" 
                                      favorites-portlet-card-size="small" 
                                      grid-portlet-card-size="auto" 
                                      hide-action-mode="never" 
                                      show-favorites-in-slider="true"
                                      return-home-title="Aller à l\'accueil"
                                      return-home-target="_self"
                                      icon-type="nine-square"
                                      sign-in-url="/portail/Login"
                                      >
                                    </extended-uportal-header>';
      
      break;
      case 'extended_uportal_footer':
        $portal_domain = $_COOKIE['extended_uportal_header_portal_domain'] ?? false;
        $block['content']['#markup'] ='<extended-uportal-footer
                                        '.($portal_domain?'domain='.$portal_domain:'').'
                                        template-api-path="/commun/portal_template_api.tpl.json"
                                        links=\'[{"title":"Accessibilité : partiellement conforme"},{"title":"CGU","href":"/files/textes/droits_usage.html"},{"title":"Apereo.org","href":"https://www.apereo.org/"},{"title":"ESUP-Portail","href":"https://www.esup-portail.org/"}]\'
                                        >
                                      </extended-uportal-header>';
        
        break;
  }
  return $block;
}
?>