<?php
/** 
 * Load JS
 */
function extended_uportal_header_process_page() {
  $params = drupal_get_query_parameters();
  $cacheBuster = isset($params['test']) ? time() : date("ymd");
  drupal_add_js('/commun/extended-uportal-header.min.js?c='.$cacheBuster, 'external');
  drupal_add_js('/commun/extended-uportal-footer.min.js?c='.$cacheBuster, 'external');
}
/**
 * Declare custom blocks
 */
function extended_uportal_header_boot() {
  $params = drupal_get_query_parameters();
  if(isset($params['portal_domain'])){
    setcookie('extended_uportal_header_portal_domain',$params['portal_domain'],[
      'secure'=>true,
      'httponly'=>true
    ]);
  }
}
/**
 * Declare custom blocks
 */
function extended_uportal_header_block_info() {
  $blocks['extended_uportal_header'] = array(
    'info' => t('Extended Uportal header component'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['extended_uportal_footer'] = array(
    'info' => t('Extended Uportal footer component'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Define custom blocks
 */
function extended_uportal_header_block_view($delta) {
  $isConfidential = false;
  if (arg(0) == 'node' && is_numeric(arg(1))) {
    $nid = arg(1);
    $node = node_load($nid);
    $isConfidential = (isset($node->webform['confidential']) && $node->webform['confidential']==1);
  }
  $actual_link = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
  switch ($delta) {
    case 'extended_uportal_header':
      if($isConfidential)return;
      $portal_domain = $_COOKIE['extended_uportal_header_portal_domain'] ?? false;
      $block['content']['#markup'] ='<extended-uportal-header
                                      messages=\'[{"locales": ["fr", "fr-FR"], "messages": { "message": {"header": {"login": "Connexion ENT" } }}}]\'
                                      '.($portal_domain?'domain='.$portal_domain:'').'
                                      fname="Yakforms"
                                      template-api-path="/commun/portal_template_api.tpl.json"
                                      >
                                    </extended-uportal-header>';
      
      break;
      case 'extended_uportal_footer':
        $portal_domain = $_COOKIE['extended_uportal_header_portal_domain'] ?? false;
        $block['content']['#markup'] ='<extended-uportal-footer
                                        '.($portal_domain?'domain='.$portal_domain:'').'
                                        template-api-path="/commun/portal_template_api.tpl.json"
                                        links=\'[{"title":"Accessibilité : partiellement conforme"},{"title":"CGU","href":"/files/textes/droits_usage.html"},{"title":"Apereo.org","href":"https://www.apereo.org/"},{"title":"ESUP-Portail","href":"https://www.esup-portail.org/"}]\'
                                        >
                                      </extended-uportal-header>';
        
        break;
  }
  return $block;
}
?>
