<?php
/**
 * Declare custom blocks
 */
function esco_prolongation_boot() {
  $params = drupal_get_query_parameters();
  if(isset($params['portal_domain'])){
    variable_set('esco_prolongation_portal_domain', $params['portal_domain']);
    setcookie('esco_prolongation_portal_domain',$params['portal_domain'],[
      'secure'=>true,
      'httponly'=>true
    ]);
  }elseif(isset($_COOKIE['esco_prolongation_portal_domain'])){
    variable_set('esco_prolongation_portal_domain', $_COOKIE['esco_prolongation_portal_domain']);
  }
}
/**
 * Declare custom blocks
 */
function esco_prolongation_block_info() {
    $blocks['esco_prolongation_header'] = array(
    'info' => t('Esco Prolongation : header'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  return $blocks;
}

/**
 * Define custom blocks
 */
function esco_prolongation_block_view($delta) {
  switch ($delta) {
    case 'esco_prolongation_header':
      if (!user_is_logged_in())return;
      $portal_domain = variable_get('esco_prolongation_portal_domain',false);
      if(!$portal_domain){
        $block['content']['#markup'] = 'erreur';
      }else{
        $block['content']['#markup'] ='<esco-prolongation 
                                        domain='.$portal_domain.'
                                        context-api-url="/portail" 
                                        sign-out-url="/portail/Logout" 
                                        default-org-logo-path="/annuaire_images/default_banner_v1.jpg"
                                        default-avatar-path="/images/icones/noPictureUser.svg"
                                        default-org-icon-path="/images/partners/netocentre-simple.svg" 
                                        favorite-api-url="/portail/api/layout" 
                                        layout-api-url="/portail/api/v4-3/dlm/layout.json" 
                                        organization-api-url="/change-etablissement/rest/v2/structures/structs/" 
                                        portlet-api-url="/portail/api/v4-3/dlm/portletRegistry.json?category=All%20categories" 
                                        user-info-api-url="/portail/api/v5-1/userinfo" 
                                        user-info-portlet-url="/portail/p/ESCO-MCE"
                                        template-api-path="/commun/portal_template_api.tpl.json" 
                                        switch-org-portlet-url="/portail/p/etablissement-swapper" 
                                        favorites-portlet-card-size="small" 
                                        grid-portlet-card-size="auto" 
                                        hide-action-mode="never" 
                                        show-favorites-in-slider="true"
                                        icon-type="four-square"
                                        >
                                      </esco-hamburger-menu>';
      }
      break;
  }
  return $block;
}
?>